apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: database
  name: mongodb-welcome-service
spec:
  serviceName: mongodb-welcome-service
  replicas: 1
  selector:
    matchLabels:
      app: database
      role: mongodb-welcome-service
  template:
    metadata:
      labels:
        app: database
        role: mongodb-welcome-service
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongodb-welcome-service-container
          image: mongo:4.4.6
          command:
            - "mongod"
            - "--bind_ip"
            - "0.0.0.0"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "250Mi"
              cpu: "200m"
          ports:
            - containerPort: 27017
          volumeMounts:
            - mountPath: /data/db
              name: mongodb-welcome-service-pvc

  volumeClaimTemplates:
    - metadata:
        name: mongodb-welcome-service-pvc
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
        storageClassName: longhorn
