apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: welcome-services
  namespace: argocd
spec:
  destination:
    namespace: be-welcome-service
    server: https://kubernetes.default.svc
  project: default
  source:
    path: Manifest/apps
    repoURL: https://github.com/nvlannasik/devops-sltr-test-case.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
